# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiac < Formula
  desc "Kubernetes in Apple Containers - every node is its own lightweight VM"
  homepage "https://github.com/saiyam1814/kiac"
  version "0.3.1"
  license "MIT"

  depends_on "kubernetes-cli"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/saiyam1814/kiac/releases/download/v0.3.1/kiac_0.3.1_darwin_arm64.tar.gz"
    sha256 "2badc978e02b54b471238aa0ce03eee71a29e2410191967e7f5d3544d9aba521"

    def install
      bin.install "kiac"
    end
  end

  def caveats
    <<~EOS
      kiac needs apple/container 1.0+:
        https://github.com/apple/container/releases
      Then: kiac doctor
    EOS
  end
end
