# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiac < Formula
  desc "Kubernetes in Apple Containers - every node is its own lightweight VM"
  homepage "https://github.com/saiyam1814/kiac"
  version "0.4.0"
  license "MIT"

  depends_on "kubernetes-cli"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/saiyam1814/kiac/releases/download/v0.4.0/kiac_0.4.0_darwin_arm64.tar.gz"
    sha256 "208d24b0a97463cabd2dc6cbc9c4cb2d0a12c664c35e148a8a79d14e334ce0f0"

    def install
      bin.install "kiac"
    end
  end

  def caveats
    <<~EOS
      kiac needs apple/container 1.0+:
        https://github.com/apple/container/releases
      Then: kiac doctor
    EOS
  end
end
