# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiac" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "b3facac3417029947dad652e09991abe6214f815afe5aa59e4efad386aba1dcb"
      url "https://github.com/saiyam1814/kiac/releases/download/v#{version}/kiac_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/saiyam1814/kiac/"
    end
  end

  name "kiac"
  desc "Kubernetes in Apple Containers - every node is its own lightweight VM"
  homepage "https://github.com/saiyam1814/kiac"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kiac"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiac"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kiac needs apple/container 1.0+ (skip 1.2.0; use 1.2.1 or newer):
      https://github.com/apple/container/releases
    Then: kiac doctor
  EOS
end
