# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiac" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kiac"]
    end
  end

  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "57f641404217984ec792883fe1ec24a013185b0d4e98599dbdc85b2b0b8edf22"
      url "https://github.com/saiyam1814/kiac/releases/download/v#{version}/kiac_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "kiac"
  desc "Kubernetes in Apple Containers - every node is its own lightweight VM"
  homepage "https://github.com/saiyam1814/kiac"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kiac"

  # No zap stanza required

  caveats <<~EOS
    kiac needs apple/container 1.0+ (1.4.1 recommended; skip 1.2.0):
      https://github.com/apple/container/releases
    Then: kiac doctor
  EOS
end
